CREATE TABLE IF NOT EXISTS table_m3 (
    "Row ID" VARCHAR,
    "Order ID" VARCHAR,
    "Order Date" DATE,
    "Ship Date" DATE,
    "Ship Mode" VARCHAR,
    "Customer ID" VARCHAR,
    "Customer Name" VARCHAR,
    "Segment" VARCHAR,
    "Country" VARCHAR,
    "City" VARCHAR,
    "State" VARCHAR,
    "Postal Code" VARCHAR,
    "Region" VARCHAR,
    "Retail Sales People" VARCHAR,
    "Product ID" VARCHAR,
    "Category" VARCHAR,
    "Sub-Category" VARCHAR,
    "Product Name" VARCHAR,
    "Returned" VARCHAR,
    "Sales" FLOAT,
    "Quantity" INT,
    "Discount" FLOAT,
    "Profit" FLOAT
)
